### PR TITLE
Various fixes, tweaks and changes

### PR DESCRIPTION
**Pull request by boskee**
- Use PRODUCT_NAME instead of "Desura" or "Desurium" wherever possible (I left service names, file names and registry keys intact)
- Fixed LanguageManager so that it actually uses Desurium in GPL build
- Fixed some of the warnings given by compiler
- Replaced DESURA_NONGPL_BUILD with DESURA_OFFICIAL_BUILD since the former wasn't defined anywhere and DESURA_OFFICIAL_BUILD is (in branding_desura/branding.h)
- Added *~ (gedit's tmp files) to .gitignore

### CODE REVIEW

**Comment by boskee** [comment]
Sorry guys, I need to learn git properly as my rebase included your changes for some reason. I will send a new request soon.

**Comment by Jookia** [comment]
No problem man. Would you be interested in running cppcheck through the code sometime?

**Comment by boskee** [comment]
Sure. I just did and there are some errors, including memory leaks, although not in my changes. I fixed 2 warnings/errors and will make a pull request along with my other changes.

**Comment by Jookia** [comment]
Wait.. what?

**Pull request merged**
