### PR TITLE
some wxWidgets 2.9.4 stuff

### PR DESCRIPTION
**Pull request by karolherbst**
this won't fix the bug, but @TheSiege noticed some improvements with wxGTK-2.9.3

I don't know If I will find the fix for other part of the bug.

NOTE: this is a candidate for the stable branch

### CODE REVIEW

**Comment by karolherbst** [comment]
I want to merge this on Sunday

**Comment by karolherbst** [comment]
I will merge this today

**Comment by karolherbst** [comment]
I didn't notice any difference. @TheSiege why does this patches improve stuff with wxGTK-2.9.3?

**Comment by TheSiege** [comment]
it got less laggy when rezising for me when the patches got applied

**Comment by karolherbst** [comment]
for me resizing to smaller sizes was always faster. Resizing to bigger sizes was the problem. But I didn't notice any differences with this pull request.

**Comment by karolherbst** [comment]
But anyway, it doesn't seem to harm anything

**Pull request merged**
