### PR TITLE
Fixed boost throwing an exception parsing date string

### PR DESCRIPTION
**Pull request by lodle**

### CODE REVIEW

**Comment by karolherbst** [comment]
I am fine with this, but we should try to be more strict about proper commit messages. There are some changes wich belongs in the first commit, but are in the second one.

We should talk about QA and what is required before commits get merged.

**Comment by lodle** [comment]
Looking back the first commit is not needed at all. Im open to ideas but it doesnt bother me that much that a bit of noise gets into the commits.

**Comment by karolherbst** [comment]
yeah, that's the reason why we should talk about it, so we have an objective set of rules we can al stick to

**Comment by karolherbst** [comment]
Is there a way how to reproduce this bug, so I can check this?

**Comment by lodle** [comment]
Look at the unit tests?

**Comment by karolherbst** [comment]
yeah, :(

**Comment by lodle** [comment]
With out this fix try installing a game. It should fail on setting the date stamp on the file every time and spam the console.

**Comment by karolherbst** [comment]
ahh, I actually saw this I think

**Comment by lodle** [comment]
And you sat there and did nothing :D

**Comment by karolherbst** [comment]
This was some days ago, actually after this request :D

**Comment by karolherbst** [comment]
@lodle cleaned up branch is here: https://github.com/karolherbst/Desurium/tree/bugfix633

**Comment by karolherbst** [comment]
merged in de8644fa53a7998dcc7f0a569e225dec2c39abab

**Pull request closed without merging**
