### PR TITLE
Port to Boost::filesystem3

### LINKED ISSUE #261: boost::filesystem2 removed in boost 1.50
we have to port to boost::filesystem3

### PR DESCRIPTION
**Pull request by karolherbst**
most of the changes were just trivial, for the non-trivial one I created some test cases.

open for testing

compiles for:
- karolherbst (gentoo, clang-3.1, gcc-4.7, boost-1.49, glibc-2.15)
- matthiaskrgr (arch, gcc-4.7, boost-1.50, glibc-2.16)
- Smilex

fixes #261

### CODE REVIEW

**Comment by Jookia** [comment]
You've narrowed the paths. Does this still work with Unicode?

**Comment by karolherbst** [comment]
``` c++
  class BOOST_FILESYSTEM_DECL path
  {
  public:

    //  value_type is the character type used by the operating system API to
    //  represent paths.

#   ifdef BOOST_WINDOWS_API
    typedef wchar_t                                     value_type;
#   else 
    typedef char                                        value_type;
#   endif
    typedef std::basic_string<value_type>               string_type;
```

so on windows boost::filesystem::path is still using wstring

On Unix file operations are fine with UTF-8 strings. Maybe I should create some tests to cover this behaviour.

Further there is no boost::filesystem::wpath anymore:

``` c++
# ifndef BOOST_FILESYSTEM_NO_DEPRECATED
  typedef path wpath;
# endif
```

**Comment by Jookia** [comment]
Where's string_type used? Tests would be great.

**Comment by karolherbst** [comment]
string_type is used internally in boost::filesystem::path

**Comment by karolherbst** [comment]
so this fixes our problems with boost-1.50 (dropped filesystem-v2)

**Comment by karolherbst** [comment]
there is currently an error in the util_fs_getAllFiles  test. I will fix this when I'm home, this could be Sunday or Monday

**Comment by karolherbst** [comment]
okay 7 out of 7 tests pass for matthiaskgr, I want to merge this on thursday, so testing, testing, testing guys

**Pull request merged**
