### PR TITLE
improve generated desktop file

### PR DESCRIPTION
**Pull request by karolherbst**
with this patches it should be possible to install the cmake generated desktop file.

NOTE: this is a candidate for the stable branch

### CODE REVIEW

**Comment by Mailaender** [comment]
:+1:

**Comment by karolherbst** [comment]
I want to use domenu in the ebuild instead of installing it via cmake.

I will change this today or tomorrow

**Comment by Mailaender** [comment]
Does Gentoo not support http://freedesktop.org/wiki/Software/desktop-file-utils?

**Comment by karolherbst** [comment]
on gentoo, there are plattform independent tools (which will use desktop-file-utils on Linux)

**Pull request merged**
