### PR TITLE
Cppcheck fixes

### PR DESCRIPTION
**Pull request by karolherbst**
This series of patches are moving member initialization into initialization list to aviod double setting of memvers.

```
Class
{
private:
  std::string str
public:
  Class()
  {
    str = "a String";
  }
}
```

will result into something like this (metacode):
1. alloc mem of Class
2. str = std::string()
3. entering constructore budy
4. str = std::("a String")

instead of setting member vars in the constructor body, we should move them out like this:

```
Class
{
private:
  std::string str
public:
  Class()
  :  str("a String")
  {}
}
```

this will result in this:
1. alloc mem of Class
2. str = std::string("a String")
3, entering constructore body (should be optimized out, because it is doing nothing)

This saves around 9kB of binary size with clang-3.1 on my system

Second thing I've done is replacing size() == 0 and size() > 0 calls with empty() and !empty(). size() could be linear complexitiy (depends on implementation), but empty() has always constant complexity.

### CODE REVIEW

**Comment by karolherbst** [comment]
I didn't find any errors here

**Comment by TheSiege** [comment]
can't find errors ... doesn't brake stuff ... ready for pull?

**Comment by karolherbst** [comment]
The Stupid thing about this request is this commit: 3f9fc78090ed362db5bbd754edf6097153b51f40

I want to have at least three reviews on it and/or some unit tests

**Comment by matthiaskrgr** [comment]
What's the cppcheck command you used?

**Comment by matthiaskrgr** [comment]
on   888ecf4b086368e8b2db27ec9299c3e5ff589eee :
cppcheck src --enable=performance,portability,unusedFunction,missingInclude --force --quiet

```
[src/shared/mcfcore/code/thread/MCFServerCon.cpp:152] -> [src/shared/mcfcore/code/thread/MCFServerCon.cpp:153]: (performance) Variable 'm_uiDPRId' is reassigned a value before the old one has been used.
[src/shared/servicecore/code/McfInit.cpp:37] -> [src/shared/servicecore/code/McfInit.cpp:57]: (performance) Variable 'res' is reassigned a value before the old one has been used.
[src/shared/servicecore/code/McfInit.cpp:37] -> [src/shared/servicecore/code/McfInit.cpp:52]: (performance) Variable 'res' is reassigned a value before the old one has been used.
[src/shared/usercore/code/BDManager.cpp:37]: (performance) Prefer prefix ++/-- operators for non-primitive types.
[src/shared/usercore/code/BDManager.cpp:51]: (performance) Prefer prefix ++/-- operators for non-primitive types.
[src/shared/usercore/code/BDManager.cpp:91]: (performance) Prefer prefix ++/-- operators for non-primitive types.
[src/shared/usercore/code/BDManager.cpp:97]: (performance) Prefer prefix ++/-- operators for non-primitive types.
[src/shared/usercore/code/CDKeyManager.cpp:111]: (performance) Prefer prefix ++/-- operators for non-primitive types.
[src/shared/usercore/code/ItemInfo.cpp:1243]: (performance) Possible inefficient checking for 'm_mBranchInstallInfo' emptiness.
[src/shared/usercore/code/ItemInfo.cpp:1462]: (performance) Possible inefficient checking for 'm_mBranchInstallInfo' emptiness.
[src/shared/usercore/code/ItemThread.cpp:247] -> [src/shared/usercore/code/ItemThread.cpp:250]: (performance) Variable 'hasTasks' is reassigned a value before the old one has been used.
[src/shared/usercore/code/ToolInfo.cpp:89]: (performance) Variable 'm_szVal' is assigned in constructor body. Consider performing initialization in initialization list.
[src/shared/usercore/code/UploadPrepThread.cpp:43] -> [src/shared/usercore/code/UploadPrepThread.cpp:53]: (performance) Variable 'validMcf' is reassigned a value before the old one has been used.
[src/shared/usercore/code/UserTasks.cpp:351]: (performance) Variable 'm_vFileList' is assigned in constructor body. Consider performing initialization in initialization list.
[src/shared/webcore/code/WebCore_Internal.cpp:56]: (performance) Prefer prefix ++/-- operators for non-primitive types.
[src/static/util/code/UtilMisc.cpp:417]: (performance) Function parameter 'file' should be passed by reference.
[src/static/util/code/UtilMisc_ico.cpp:79] -> [src/static/util/code/UtilMisc_ico.cpp:83]: (performance) Variable 'fif' is reassigned a value before the old one has been used.
[src/static/util/code/UtilString.cpp:611]: (performance) Prefer prefix ++/-- operators for non-primitive types.
[src/static/util/code/UtilWindows.cpp:735] -> [src/static/util/code/UtilWindows.cpp:748]: (performance) Variable 'res' is reassigned a value before the old one has been used.
[src/static/util/code/UtilWindows_dotnet.cpp:319] -> [src/static/util/code/UtilWindows_dotnet.cpp:322]: (performance) Variable 'bRegistryRetVal' is reassigned a value before the old one has been used.
[src/static/util_bootloader/code/CreateProcess.cpp:90] -> [src/static/util_bootloader/code/CreateProcess.cpp:91]: (performance) Variable 'hr' is reassigned a value before the old one has been used.
[src/static/util_thread/code/ThreadPool.cpp:315]: (performance) Prefer prefix ++/-- operators for non-primitive types.
[src/static/util/code/third_party/GeneralHashFunctions.cpp:221]: (style) The function 'APHash' is never used.
[src/static/util/code/third_party/WinXPSP2FireWall.cpp:392]: (style) The function 'AddPort' is never used.
[src/static/util/code/third_party/GeneralHashFunctions.cpp:116]: (style) The function 'BKDRHash' is never used.
[src/static/util/code/third_party/GeneralHashFunctions.cpp:173]: (style) The function 'BPHash' is never used.
[src/static/wx_controls/code/guiDelegate.cpp:54]: (style) The function 'Clone' is never used.
[src/shared/uicore/code/TaskBarIcon.cpp:183]: (style) The function 'CreatePopupMenu' is never used.
[src/static/util/code/third_party/GeneralHashFunctions.cpp:159]: (style) The function 'DEKHash' is never used.
[src/static/util/code/third_party/GeneralHashFunctions.cpp:145]: (style) The function 'DJBHash' is never used.
[src/shared/uicore/code/UICoreMain.cpp:47]: (style) The function 'DllMain' is never used.
[src/static/util/code/third_party/GeneralHashFunctions.cpp:96]: (style) The function 'ELFHash' is never used.
[src/static/util_bootloader/code/third_party/PEImage.cpp:494]: (style) The function 'EnumAllDelayImports' is never used.
[src/static/util_bootloader/code/third_party/PEImage.cpp:389]: (style) The function 'EnumAllImports' is never used.
[src/static/util_bootloader/code/third_party/PEImage.cpp:255]: (style) The function 'EnumExports' is never used.
[src/static/util_bootloader/code/third_party/PEImage.cpp:309]: (style) The function 'EnumRelocs' is never used.
[src/static/util_bootloader/code/third_party/PEImage.cpp:239]: (style) The function 'EnumSections' is never used.
[src/shared/uicore/code/Managers.cpp:111]: (style) The function 'ExitApp' is never used.
[src/shared/uicore/code/UICoreMain.cpp:518]: (style) The function 'ExitMainLoop' is never used.
[src/static/util/code/third_party/GeneralHashFunctions.cpp:186]: (style) The function 'FNVHash' is never used.
[src/shared/servicecore/code/ServiceCoreMain.cpp:80]: (style) The function 'FactoryBuilderSC' is never used.
[src/shared/scriptcore/code/ScriptCoreMain.cpp:124]: (style) The function 'FactoryBuilderScriptCore' is never used.
[src/shared/webcore/code/WebCoreMain.cpp:110]: (style) The function 'FactoryBuilderWC' is never used.
[src/static/mdump/code/MiniDumpGenerator_win.cpp:317]: (style) The function 'GUIDToSymbolServerWString' is never used.
[src/static/mdump/code/MiniDumpGenerator_win.cpp:300]: (style) The function 'GUIDToWString' is never used.
[src/shared/uicore/code/MainFormCustomFrame.cpp:147]: (style) The function 'GetClientAreaOrigin' is never used.
[src/static/util_bootloader/code/third_party/PEImage.cpp:131]: (style) The function 'GetImageSectionHeaderByName' is never used.
[src/shared/uicore/code/UICoreMain.cpp:59]: (style) The function 'GetMainThreadId' is never used.
[src/executable/desura_browserhost/code/CefEvents_Js.cpp:71]: (style) The function 'HandleJSBinding' is never used.
[src/executable/desura_browserhost/code/CefEvents.cpp:84]: (style) The function 'HandleWndProc' is never used.
[src/static/util_bootloader/code/third_party/PEImage.cpp:521]: (style) The function 'ImageRVAToOnDiskOffset' is never used.
[src/static/util/code/UtilWindows_dotnet.cpp:391]: (style) The function 'IsCurrentOSTabletMedCenter' is never used.
[src/static/util/code/third_party/WinXPSP2FireWall.cpp:501]: (style) The function 'IsExceptionNotAllowed' is never used.
[src/static/util/code/third_party/WinXPSP2FireWall.cpp:553]: (style) The function 'IsNotificationDiabled' is never used.
[src/static/util/code/third_party/WinXPSP2FireWall.cpp:602]: (style) The function 'IsUnicastResponsesToMulticastBroadcastDisabled' is never used.
[src/static/util/code/third_party/GeneralHashFunctions.cpp:58]: (style) The function 'JSHash' is never used.
[src/shared/uicore/code/Managers.cpp:36]: (style) The function 'LangChanged' is never used.
[src/static/wx_controls/code/gcButton.cpp:51]: (style) The function 'MSWCommand' is never used.
[src/shared/usercore/code/McfManager.cpp:53]: (style) The function 'McfInfoSort' is never used.
[src/executable/bootloader_win/code/UpdateFunctions.cpp:304]: (style) The function 'MoveDataFolder' is never used.
[src/shared/uicore/code/UICoreMain.cpp:525]: (style) The function 'OnAssert' is never used.
[src/executable/bootloader_win/code/DesuraMain.cpp:454]: (style) The function 'OnIdle' is never used.
[src/shared/uicore/code/UICoreMain.cpp:411]: (style) The function 'OnInit' is never used.
[src/shared/uicore/code/MainApp_cvar.cpp:303]: (style) The function 'OnLinuxArgsChange' is never used.
[src/shared/uicore/code/MainApp_cvar.cpp:292]: (style) The function 'OnLinuxBinChange' is never used.
[src/static/util/code/third_party/GeneralHashFunctions.cpp:72]: (style) The function 'PJWHash' is never used.
[src/static/wx_controls/code/gcCustomFrameImpl.cpp:266]: (style) The function 'PostMSWWindowProc' is never used.
[src/static/wx_controls/code/gcCustomFrameImpl.cpp:171]: (style) The function 'PreMSWWindowProc' is never used.
[src/common/LogBones.cpp:25]: (style) The function 'PrintfMsg' is never used.
[src/shared/scriptcore/code/ScriptCoreMain.cpp:134]: (style) The function 'RegDLLCB_SCRIPT' is never used.
[src/static/mdump/code/MiniDumpGenerator_win.cpp:278]: (style) The function 'Register' is never used.
[src/static/wx_controls/code/gcTaskBar.cpp:320]: (style) The function 'RemoveIcon' is never used.
[src/static/util/code/third_party/WinXPSP2FireWall.cpp:461]: (style) The function 'RemovePort' is never used.
[src/static/mdump/code/MiniDumpGenerator_win.cpp:283]: (style) The function 'RequestDump' is never used.
[src/shared/uicore/code/UICoreEntry.cpp:358]: (style) The function 'RestartAndSetMCFCache' is never used.
[src/executable/bootloader_lin/code/DesuraMain.cpp:118]: (style) The function 'RestartBootloader' is never used.
[src/executable/desura_browserhost/code/CefBrowserLoader.cpp:95]: (style) The function 'RestartTimerCB' is never used.
[src/static/util/code/third_party/GeneralHashFunctions.cpp:131]: (style) The function 'SDBMHash' is never used.
[src/static/util/code/third_party/WinXPSP2FireWall.cpp:532]: (style) The function 'SetExceptionNotAllowed' is never used.
[src/static/util/code/third_party/WinXPSP2FireWall.cpp:581]: (style) The function 'SetNotificationDiabled' is never used.
[src/static/util/code/third_party/WinXPSP2FireWall.cpp:630]: (style) The function 'SetUnicastResponsesToMulticastBroadcastDisabled' is never used.
[src/shared/uicore/code/UICoreMain.cpp:218]: (style) The function 'ShowAssertDialog' is never used.
[src/shared/uicore/code/Managers.cpp:57]: (style) The function 'ThemeChanged' is never used.
[src/static/util/code/third_party/WinXPSP2FireWall.cpp:137]: (style) The function 'TurnOffWindowsFirewall' is never used.
[src/static/util/code/third_party/WinXPSP2FireWall.cpp:105]: (style) The function 'TurnOnWindowsFirewall' is never used.
[src/static/managers/code/ConCommandManager.cpp:58]: (style) The function 'UnRegCCom' is never used.
[src/shared/crashuploader/code/CrashuploaderMain.cpp:110]: (style) The function 'UploadCrash' is never used.
[src/shared/crashuploader/code/CrashuploaderMain.cpp:115]: (style) The function 'UploadCrashProg' is never used.
[src/static/util_bootloader/code/third_party/PEImage.cpp:500]: (style) The function 'VerifyMagic' is never used.
[src/shared/usercore/code/ItemInfo.cpp:882]: (style) The function 'addPFlag' is never used.
[src/shared/uicore/code/TabHandler.cpp:46]: (style) The function 'addPanel' is never used.
[src/static/util/code/UtilWeb.cpp:694]: (style) The function 'addRawPost' is never used.
[src/static/scriptengine/code/jsExtensions.cpp:186]: (style) The function 'addRef' is never used.
[src/shared/uicore/code/MainApp_internal.cpp:41]: (style) The function 'admin_cb' is never used.
[src/shared/uicore/code/MainApp_cvar.cpp:406]: (style) The function 'autoStartChange' is never used.
[src/static/util/code/UtilString.cpp:421]: (style) The function 'base64_decodeCB' is never used.
[src/static/util/code/UtilString.cpp:549]: (style) The function 'base64_encodeCB' is never used.
[src/shared/uicore/code/MainApp_cvar.cpp:354]: (style) The function 'betaChange' is never used.
[src/shared/utilcore/code/BZip2.cpp:75]: (style) The function 'bz2CompressFile' is never used.
[src/shared/usercore/code/ItemInfo.cpp:945]: (style) The function 'compare' is never used.
[src/shared/uicore/code/MainApp_cvar.cpp:385]: (style) The function 'corecountChange' is never used.
[src/shared/usercore/code/ItemInfo.cpp:887]: (style) The function 'delPFlag' is never used.
[src/static/umcf/code/UMcf.cpp:690]: (style) The function 'deleteAllFiles' is never used.
[src/static/scriptengine/code/jsExtensions.cpp:125]: (style) The function 'deleteValue' is never used.
[src/shared/usercore/code/ItemHandleEvents.cpp:191]: (style) The function 'deregisterTask' is never used.
[src/static/ipc_pipe/code/IPCClass.cpp:79]: (style) The function 'deserializeList' is never used.
[src/static/umcf/code/UMcf.cpp:259]: (style) The function 'disableMoveOldFiles' is never used.
[src/static/util_fs/code/UtilFs.cpp:194]: (style) The function 'eraseFolder' is never used.
[src/static/util/code/UtilWindows.cpp:774]: (style) The function 'extractIconCB' is never used.
[src/shared/uicore/code/ItemForm.cpp:616]: (style) The function 'finishUninstall' is never used.
[src/shared/uicore/code/CreateProgPage.cpp:205]: (style) The function 'finished' is never used.
[src/shared/uicore/code/MainApp_cvar.cpp:314]: (style) The function 'forceShortcutChange' is never used.
[src/shared/uicore/code/ItemForm.cpp:117]: (style) The function 'gatherInfoComplete' is never used.
[src/shared/uicore/code/DesuraControl.cpp:454]: (style) The function 'getActivePage' is never used.
[src/static/util/code/UtilWindows.cpp:365]: (style) The function 'getAllRegValues' is never used.
[src/shared/usercore/code/ItemManager.cpp:322]: (style) The function 'getDevItemCount' is never used.
[src/shared/mcfcore/code/mcf/MCFFile.cpp:834]: (style) The function 'getDiffHash' is never used.
[src/shared/mcfcore/code/mcf/MCFFile.cpp:839]: (style) The function 'getDiffOrgFileHash' is never used.
[src/shared/usercore/code/ItemHandle.cpp:1345]: (style) The function 'getEventHandler' is never used.
[src/static/managers/code/CVar.cpp:104]: (style) The function 'getFloat' is never used.
[src/static/util_fs/code/UtilFs.cpp:110]: (style) The function 'getFolderSize' is never used.
[src/static/scriptengine/code/jsExtensions.cpp:172]: (style) The function 'getFunctionName' is never used.
[src/static/util/code/UtilWindows.cpp:420]: (style) The function 'getHDDSerial' is never used.
[src/shared/uicore/code/MainApp.cpp:539]: (style) The function 'getLoginEvent' is never used.
[src/shared/usercore/code/User_nix.cpp:72]: (style) The function 'getLoginInfo' is never used.
[src/shared/usercore/code/McfManager.cpp:492]: (style) The function 'getMCFFiles' is never used.
[src/shared/usercore/code/ToolInfo.cpp:298]: (style) The function 'getNameId' is never used.
[src/shared/mcfcore/code/MCFDPReporter.cpp:42]: (style) The function 'getProviderCount' is never used.
[src/shared/mcfcore/code/MCFDPReporter.cpp:47]: (style) The function 'getProviderId' is never used.
[src/shared/usercore/code/DownloadToolTask.cpp:135]: (style) The function 'getRefCount' is never used.
[src/shared/webcore/code/WebCore.cpp:107]: (style) The function 'getRefreshUrl' is never used.
[src/shared/uicore/code/TabControl.cpp:49]: (style) The function 'getTab' is never used.
[src/shared/mcfcore/code/MCFDPReporter.cpp:115]: (style) The function 'getTotalSinceStart' is never used.
[src/static/managers/code/CVar.cpp:221]: (style) The function 'getUserData' is never used.
[src/static/util/code/UtilWeb.cpp:557]: (style) The function 'getWebToFile' is never used.
[src/shared/mcfcore/code/mcf/MCF.cpp:900]: (style) The function 'getWriteHandle' is never used.
[src/static/util/code/UtilMisc.cpp:407]: (style) The function 'hashString' is never used.
[src/shared/webcore/code/WebCore_Internal.cpp:150]: (style) The function 'hashToId' is never used.
[src/shared/uicore/code/HeaderButton.cpp:116]: (style) The function 'inverseSortDir' is never used.
[src/shared/uicore/code/MainApp.cpp:336]: (style) The function 'isQuietMode' is never used.
[src/static/scriptengine/code/jsExtensions.cpp:40]: (style) The function 'isUndefined' is never used.
[src/static/wx_controls/code/gcCustomFrameImpl.cpp:348]: (style) The function 'maximize' is never used.
[src/static/wx_controls/code/gcCustomFrameImpl.cpp:388]: (style) The function 'minimize' is never used.
[src/static/util_fs/code/UtilFs.cpp:162]: (style) The function 'moveFolder' is never used.
[src/static/util/code/UtilWeb.cpp:249]: (style) The function 'newHttpHandle' is never used.
[src/common/service_pipe/IPCServiceMain.cpp:240]: (style) The function 'newUpdateApp' is never used.
[src/shared/uicore/code/BaseInstallPage.cpp:37]: (style) The function 'onChangeStage' is never used.
[src/shared/uicore/code/UploadProgPage.cpp:178]: (style) The function 'onChecked' is never used.
[src/shared/utilcore/code/ToolInstallForm.cpp:100]: (style) The function 'onConnect' is never used.
[src/executable/desura_browserhost/code/CefEvents.cpp:49]: (style) The function 'onJScriptAlert' is never used.
[src/executable/desura_browserhost/code/CefEvents.cpp:54]: (style) The function 'onJScriptConfirm' is never used.
[src/executable/desura_browserhost/code/CefEvents.cpp:59]: (style) The function 'onJScriptPrompt' is never used.
[src/executable/desura_browserhost/code/CefEvents.cpp:79]: (style) The function 'onLoadError' is never used.
[src/shared/uicore/code/ItemTabPage.cpp:295]: (style) The function 'onSearchText' is never used.
[src/static/util/code/UtilMisc.cpp:590]: (style) The function 'operatorchar*' is never used.
[src/shared/usercore/code/ItemInfo.cpp:1561]: (style) The function 'overrideMcfBuild' is never used.
[src/shared/mcfcore/code/mcf/MCF.cpp:395]: (style) The function 'printAll' is never used.
[src/static/ipc_pipe/code/IPCPipeBase_Nix.cpp:28]: (style) The function 'print_buffer' is never used.
[src/executable/desura_browserhost/code/CefThemeLoader.cpp:32]: (style) The function 'processRequest' is never used.
[src/shared/uicore/code/MainApp_wildcards.cpp:29]: (style) The function 'processWildCards' is never used.
[src/static/umcf/code/UMcf.cpp:461]: (style) The function 'progressUpdate' is never used.
[src/static/ipc_pipe/code/IPCManager.cpp:114]: (style) The function 'purgeEvents' is never used.
[src/static/util_fs/code/UtilFs.cpp:72]: (style) The function 'readCB' is never used.
[src/static/ipc_pipe/code/IPCClass.cpp:274]: (style) The function 'registerEvent' is never used.
[src/common/gcJSBase.cpp:268]: (style) The function 'registerFunction' is never used.
[src/shared/mcfcore/code/mcf/MCF.cpp:603]: (style) The function 'removeIncompleteFiles' is never used.
[src/shared/mcfcore/code/MCFDPReporter.cpp:120]: (style) The function 'resetStart' is never used.
[src/static/wx_controls/code/gcCustomFrameImpl.cpp:333]: (style) The function 'restore' is never used.
[src/shared/webcore/code/WebCore_External.cpp:41]: (style) The function 'sendPassReminder' is never used.
[src/shared/uicore/code/DesuraControl.cpp:418]: (style) The function 'setBaseTabPage' is never used.
[src/static/ipc_pipe/code/IPCManager.cpp:630]: (style) The function 'setItemHashId' is never used.
[src/shared/uicore/code/MainFormCustomFrame.cpp:155]: (style) The function 'setMenuHover' is never used.
[src/static/util/code/UtilWeb.cpp:745]: (style) The function 'setOutFile' is never used.
[src/static/wx_controls/code/gcImageControl.cpp:69]: (style) The function 'setPropotional' is never used.
[src/static/wx_controls/code/gcGrid.cpp:53]: (style) The function 'setToolTip' is never used.
[src/static/wx_controls/code/gcHyperlinkCtrl.cpp:63]: (style) The function 'setUnderlined' is never used.
[src/static/managers/code/CVar.cpp:216]: (style) The function 'setUserData' is never used.
[src/static/util_bootloader/code/third_party/PEImage.cpp:71]: (style) The function 'set_module' is never used.
[src/shared/uicore/code/ItemForm.cpp:815]: (style) The function 'showComplexLaunchPrompt' is never used.
[src/shared/uicore/code/ItemForm.cpp:810]: (style) The function 'showLaunchPrompt' is never used.
[src/shared/servicecore/code/McfInit.cpp:102]: (style) The function 'shutDownFactory' is never used.
[src/static/util/code/UtilString.cpp:89]: (style) The function 'splitURL' is never used.
[src/static/managers/code/WindowManager.cpp:58]: (style) The function 'unRegisterWindow' is never used.
[src/static/util/code/UtilWindows_service.cpp:415]: (style) The function 'uninstallService' is never used.
[src/static/umcf/code/UMcf.cpp:456]: (style) The function 'updateAllCB' is never used.
[src/shared/uicore/code/DesuraControl.cpp:362]: (style) The function 'updateStatusBar' is never used.
[src/shared/uicore/code/MainApp_cvar.cpp:337]: (style) The function 'updoaddumpsChange' is never used.
[src/shared/uicore/code/LoginForm.cpp:44]: (style) The function 'validateUsernameChange' is never used.
[src/shared/mcfcore/code/mcf/MCF.cpp:845]: (style) The function 'verifyUnitTest' is never used.
(information) Cppcheck cannot find all the include files (use --check-config for details)
```

**Comment by karolherbst** [comment]
@matthiaskrgr: don't know I used cppcheck-gui, which enables everything by deafult

**Pull request merged**
