### PR TITLE
Forced desura to save settings on login to ensure auto login settings al...

### PR DESCRIPTION
**Pull request by lodle**
...ways apply #640

### CODE REVIEW

**Comment by karolherbst** [comment]
Seems save to me

**Comment by karolherbst** [comment]
what happens with a wrong password?

**Comment by lodle** [comment]
this is for the auto login settings, as if the app doesnt close nicely the settings dont get saved at all causing auto login to be disabled next startup

**Comment by karolherbst** [comment]
I am just worried what happens if you check auto login, fill in username and a wrong password and quit the client after that

**Comment by lodle** [comment]
It will just return to the login form. Not something im worried about. Auto login requires one good login to work

**Comment by karolherbst** [comment]
okay

**Pull request merged**
