### PR TITLE
Update build_out/data/language/hungarian_utility.xml

### PR DESCRIPTION
**Pull request by AllenWalkerHU**
Fully retranslated "english_utility.xml" to Hungarian.

### CODE REVIEW

**Comment by Jookia** [comment]
Does this account for https://github.com/lodle/Desurium/wiki/Translation-TODO ?

**Comment by AllenWalkerHU** [comment]
Really sorry but I don't get what this question means.

**Comment by Jookia** [comment]
Ah, I mean that since the previous translations were done, new things have been added that aren't in the translations. They're in that list there. Does your new translation include the changes?

**Comment by AllenWalkerHU** [comment]
Oh, now I see. Well, they aren't included YET, since I've just registered here about half an hour ago after I finished translating that file and didn't really had time to check everything here. But I'll update every one of what I missed.

**Comment by karolherbst** [comment]
Is this patch tested against our current master/0.8 branch? Because it would make sense to merge this also into the 0.8 branch.

**Comment by karolherbst** [comment]
closed because of #379

**Comment by AllenWalkerHU** [comment]
What's wrong with this one? I don't think I missed or mistranslated any string. Also checked it with the 0.8 branch and it's ready to be merged.

**Comment by Jookia** [comment]
I'm a little confused too.

**Comment by karolherbst** [comment]
see #379

**Comment by karolherbst** [comment]
ohh my fault, I thought these both were the same file

**Comment by AllenWalkerHU** [comment]
I thought we have a bigger problem here. No worries anyway. And thanks!

**Pull request merged**
