### PR TITLE
travis overhaul

### PR DESCRIPTION
**Pull request by matthiaskrgr**
The idea is that if install-deps.sh misses some dependencies, we will directly know via the automated testing.
Comment out the two tests temporarily since they were failing.
Print travis build failure/success into #desura.

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
I couldn't test this yet though :p

**Comment by karolherbst** [comment]
nice idea :) but for testing you have to enable travis for your account and branches

**Comment by matthiaskrgr** [comment]
The build fails however I don't think it is related to my changes.https://travis-ci.org/matthiaskrgr/Desurium/builds/4114849

**Comment by matthiaskrgr** [comment]
I am dead tired but this finally works properly now.

07:05 -!- travis-ci [~travis-ci@ec2-23-23-7-244.compute-1.amazonaws.com] has joined #desura
07:05 < travis-ci> [travis-ci] matthiaskrgr/Desurium (30eab70) by matthiaskrgr : The build passed.  
07:05 < travis-ci> [travis-ci] Build details: http://travis-ci.org/matthiaskrgr/Desurium/builds/4119267
07:05 -!- travis-ci [~travis-ci@ec2-23-23-7-244.compute-1.amazonaws.com] has left #desura []

**Comment by Jookia** [comment]
(17:21:14) matthiaskrgr: karol had implemented 2 tests which were failing 
(17:21:20) matthiaskrgr: I just commented them out so far
(17:22:22) matthiaskrgr: (because I also wanted to know if everything but the test worked)

Should we be concerned about this with the merge?

**Comment by matthiaskrgr** [comment]
08:28 -!- travis-ci [~travis-ci@ec2-23-23-7-244.compute-1.amazonaws.com] has joined #desura
08:28 < travis-ci> [travis-ci] matthiaskrgr/Desurium (83554e8) by matthiaskrgr : The build was fixed.  
08:28 < travis-ci> [travis-ci] Build details: http://travis-ci.org/matthiaskrgr/Desurium/builds/4119890
08:28 < travis-ci> [travis-ci] Latest commit: https://github.com/matthiaskrgr/Desurium/compare/55d06aeeaffd...83554e861267
08:28 -!- travis-ci [~travis-ci@ec2-23-23-7-244.compute-1.amazonaws.com] has left #desura []

https://travis-ci.org/matthiaskrgr/Desurium/builds/4119890

**Comment by karolherbst** [comment]
please clean this up

1 clean commit should be enough for this changes.

In addition to that, the test is failing, because the test is not implemented right.

**Comment by Jookia** [comment]
Yeah, can you uncomment things so it does fail? Because, you know, it DOES fail.

**Comment by karolherbst** [comment]
further questions:
1. why "make clean" ?
2. why "sudo apt-get update sudo apt-get upgrade sudo ./install-deps.sh"

we should avoid stuff which will only increase build time

also the calling of the install-deps script is heavier than installing stuff, which is missing.

**Comment by matthiaskrgr** [comment]
https://github.com/matthiaskrgr/Desurium/tree/Travis squashed

**Pull request closed without merging**
