### PR TITLE
Fixed issue with desura corrupting downloads #615

### PR DESCRIPTION
**Pull request by lodle**

### CODE REVIEW

**Comment by Jookia** [comment]
@karolherbst This breaks on GCC (Travis CI at least), due to the override keyword. Are some flags not set?

**Comment by karolherbst** [comment]
also you should try to reorder the commits with git rebase. So first this #define override thing, then the actual fixes. This will prevent some issues while rebasing bugs. We should try to keep every commit compileable on every platform and the fix for this isn't that hard.

**Comment by karolherbst** [comment]
We should wait with this commit until gtest got merged

**Comment by karolherbst** [comment]
cleaned up branch: https://github.com/karolherbst/Desurium/commits/bugfix615

**Comment by karolherbst** [comment]
@lodle what do you think? https://github.com/karolherbst/Desurium/commit/cbecddf8b3fe903de00ed8ae2efbab54e8d76fcc

**Comment by lodle** [comment]
Looks good karolherbst. Merge when ready

**Pull request closed without merging**
