### PR TITLE
cef: install libffmpegsumo.so

### LINKED ISSUE #136: desurium: add webm support
Since the latest version of Flash is the last version for Linux, it's only fitting that we dump that plugin. Who's with me?

EDIT by karolherbst:
We should make desurium stable whily playin webm videos, then desura could replace their flash videos with webm

### PR DESCRIPTION
**Pull request by karolherbst**
fixes #136 

if you want to test this, just add

``` html
<video controls="" autoplay="" name="media"><source src="http://video.webmfiles.org/big-buck-bunny_trailer.webm" type="video/webm"></video>
```

to settings.html after <div id="gamesettings">

NOTE: this is a candidate for the stable branch
commit 0552d3aede7d778dee04f317d59305bf18ba760b requires a cef rebuild

### CODE REVIEW

**Comment by karolherbst** [comment]
works for me, I want to merge this before creating new RC

**Comment by makson96** [comment]
Is it possible to use libffmpegsumo.so directly from chromium (chromium-codecs-ffmpeg in Ubuntu):
http://packages.ubuntu.com/quantal/amd64/chromium-codecs-ffmpeg/filelist
or from Google Chrome (/opt/google/chrome)?

**Comment by karolherbst** [comment]
I tried it, but it did not work, because our CEF is based on chromium 15, which is a bit old. And because this file is builded anyway I don't see a reason to not install it.

**Comment by karolherbst** [comment]
Addition:
It could be, that I did not tried webm with chrome libffmpegsumo.so, but html5 did not work, so I don't see the real benefit of it

**Comment by TheSiege** [comment]
it seems to work; though my progress bar is screwd also:

```
[0220/182038:ERROR:alsa_output.cc(713)] Failed querying delay: Eingabe-/Ausgabefehler
[0220/182043:ERROR:alsa_output.cc(713)] Failed querying delay: Eingabe-/Ausgabefehler
[0220/182116:ERROR:alsa_output.cc(713)] Failed querying delay: Eingabe-/Ausgabefehler
[0220/182116:ERROR:alsa_output.cc(713)] Failed querying delay: Eingabe-/Ausgabefehler
[0220/182118:ERROR:alsa_output.cc(713)] Failed querying delay: Eingabe-/Ausgabefehler
```

but that could just be me

**Comment by karolherbst** [comment]
I am getting the same error, but I think this won't harm anything, maybe alsa is compiled too and does not work well while a system one is running?

**Comment by karolherbst** [comment]
I will merge this, because webm will be only in a testing state. Also it is required to get finally H.264 support, but I don't want to enabled this before we discussed potential legal problems

**Pull request merged**
