### PR TITLE
Default 32bit support on 64bit Linux

### PR DESCRIPTION
**Pull request by makson96**
I guess that most gamers on 64 bit system want their 32 bit games to work by default. install-deps.sh already provides all dependencies for building this support (at least on Ubuntu and Debian).

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
Hmm, perhaps we should rather implement an 32bit option into build_desura.sh ?

**Comment by makson96** [comment]
I can do that, but I am not in favor of it. If we add to many options into build_desura.sh it will be no different, than just directly invoking  cmake.

Nevertheless I think that 32bit support should be enabled by default, because all gamers do expect it.

**Comment by karolherbst** [comment]
I think this will lead into the same problems, but the other way around (try 32bit build on non multilib systems).

I think the best solution would be to enable this only by default if and only if the compiler supports multilib

**Comment by makson96** [comment]
This test work for me. It will make 32 bit support enable only if test for compiling code with C flag "-m32" (on 64 bit system) is passed.

**Comment by karolherbst** [comment]
Isn't there an easier way to find this out?

**Comment by makson96** [comment]
I haven't found any by Google :P

If you have any better idea please let me know and I can use it.

**Comment by karolherbst** [comment]
did anybody test this on a non multilib 64bit system?

**Comment by makson96** [comment]
Well, I did.

On Ubuntu after uninstalling "gcc-multilib" test fails and 32 bit support is turned OFF. After installing package back and running cmake once again test is successful and 32 bit support is ON.

**Comment by Mailaender** [comment]
Requested for openSUSE on https://bugzilla.novell.com/show_bug.cgi?id=805424.

**Pull request merged**
