### PR TITLE
some cmake improvements and README update

### PR DESCRIPTION
**Pull request by karolherbst**
works for:
- karolherbst (gentoo + ebuild, gcc-4.7.1)
- TheSiege (gentoo. gcc-4.7.1 / linux mint 13, gcc-4.6.3)

### CODE REVIEW

**Comment by Jookia** [comment]
Why not just remove the SET_OWN_EXT_SRC flag, try and set the variables to the user's inputs by default and fall back on the predefined stuff? It'd allow individual sources and remove the need for all the error messages.

**Comment by karolherbst** [comment]
yeah, I will think about this over night

**Comment by TheSiege** [comment]
We could do that but then I strongly argue for being able to set the svn repos too

**Comment by karolherbst** [comment]
I don't know how to handle hashes in this case. We could enforce specific versions of packages, but I don't like the idea, because there are maybe some reasons to use a newer or older version

**Comment by TheSiege** [comment]
I'd say don't do hashes in this case. So one can experiment.

**Comment by karolherbst** [comment]
yes, but I want to avoid if clauses

**Comment by karolherbst** [comment]
but I have an idea

**Comment by karolherbst** [comment]
I rebased this request on current master so we are able to merge this cleanly. Work seems to be done. Open for testing.

**Comment by TheSiege** [comment]
works on:
gentoo gcc-4.7.1
linux mint 13 gcc-4.6.3

**Pull request merged**
