### PR TITLE
Updated release build to build with debugging information #630

### PR DESCRIPTION
**Pull request by lodle**

### CODE REVIEW

**Comment by karolherbst** [comment]
We should rework the DEBUG option anyway, I just have to figure out how to deal with external projects on windows with the cmake internal build types

**Comment by lodle** [comment]
This is for release builds though. Need the pdb files to debug crash dumps

**Comment by karolherbst** [comment]
Yeah, I know. This path can be used for creating releases, but I would like to have a more cmake aware solution. There should be a way of telling cmake when do build External builds in which way without having too much pain.

**Comment by karolherbst** [comment]
any updates here?

**Comment by lodle** [comment]
Im not sure what you want. This is the cmake solution for this.

**Comment by karolherbst** [comment]
I wanted to know what you ideas are about using RelWithDebInfo only for official builds

**Comment by lodle** [comment]
Oh can do that. Is there an issue with having it for non official builds? Debug info is always useful

**Comment by karolherbst** [comment]
yeah, but distributions want to set the flags on their own anyway

**Pull request merged**
