### PR TITLE
common: use template paramters in AutoDeleteLocal

### PR DESCRIPTION
**Pull request by karolherbst**
we have to add this to be more c++ standard compliant.

also fixes compile errors on mingw

### CODE REVIEW

**Comment by TheSiege** [comment]
still compiles on my gentoo

**Comment by karolherbst** [comment]
I want to merge this on Sunday

**Comment by karolherbst** [comment]
no build failure with visual studio, too

**Comment by Jookia** [comment]
Does this exhibit the same behaviour as the previous iteration of it? Prefixing that stuff with the parent class name looks a little weird. Is there a reason why that's done?

**Comment by karolherbst** [comment]
this code was only used with msvc, but on windows mingw, which is gcc in fact, complained about this. The error is not the missing class prefix, but the missing template argument.

**Comment by karolherbst** [comment]
compiles fine on msvc

**Pull request merged**
