### PR TITLE
uicore: fix Breadcrumbs height

### LINKED ISSUE #213: Breadcrumbs are positioned too high.
I've managed to get this fixed somehow by removing the last column, specifically changing [this line](https://github.com/lodle/Desurium/blob/master/src/shared/uicore/code/HtmlToolBarControl.cpp#L72) to having 10 columns instead of 11. But that removes the last search element.

### PR DESCRIPTION
**Pull request by karolherbst**
fixes #213

NOTE: this is a candidate for the stable branch

### CODE REVIEW

**Comment by karolherbst** [comment]
I have the same issue like Jookia, so I have to find the cause

**Comment by Jookia** [comment]
This is something that's been bugging- Oh, you posted as I was writing. Anyways, nice patch. I couldn't figure it out.

**Comment by karolherbst** [comment]
so I reverted your change, so the "/" are right, but not the home button

**Comment by Jookia** [comment]
So the home button is bugged?

**Comment by karolherbst** [comment]
yeah I have to investigate a bit further on this

**Comment by karolherbst** [comment]
I will close this, because it isn't finished yet

**Pull request closed without merging**
