### PR TITLE
Added control + c (copy) to message dialogs to copy text #373

### PR DESCRIPTION
**Pull request by lodle**

### CODE REVIEW

**Comment by karolherbst** [comment]
Shouldn't that be handled automatically? I am worried, that we are doing so much on our own and force specific key combinations, which seems to be standard, but specially on Linux you are able to rebind nrearly everything.

Isn't there a way to add the copy shortcut without knowing which it is?

**Comment by lodle** [comment]
this is only for error dialog's and control + c is very well known. Im not to worried about custom bindings.

**Comment by karolherbst** [comment]
ask the guys who are using dvorak ;) I just would loke to know if there is any other possibility as checking against WXK_CONTROL_C. If there is no, I will be fine with that.

**Comment by lodle** [comment]
From a quick google, no

**Comment by Jookia** [comment]
Maybe we should open a new issue for compatibility with keyboard shortcuts and push that back to another time.

**Comment by karolherbst** [comment]
I will test this later

**Comment by karolherbst** [comment]
cleaned up branch: https://github.com/karolherbst/Desurium/commits/bugfix373

**Comment by lodle** [comment]
moved to https://github.com/desura/Desurium/pull/682

**Pull request closed without merging**
