### PR TITLE
Bug190

### LINKED ISSUE #190: No language loaded.
I don't know what causes this, but sometimes the language strings aren't loaded.

### PR DESCRIPTION
**Pull request by karolherbst**
this could fix #190

I can't test it, because it didn't occure from me, but it is building here

compile works for:
- karolherbst (gentoo, gcc-4.7.1, clang-3.1)
- anagromataf (gentoo, gcc-4.7.1)

### CODE REVIEW

**Comment by Jookia** [comment]
Could you explain _why_ it would fix it?

**Comment by karolherbst** [comment]
maybe I will change it to "could" because Smilex wasn't sure about this

**Comment by TheSiege** [comment]
compiles and runs; though I can't reproduce #190; I can't say if it is fixed.
gentoo, gcc 4.7.1

**Comment by Jookia** [comment]
I'm not convinced that this fixes it until we can reproduce the bug. What're the other benefits to this patch?

**Comment by karolherbst** [comment]
I rebased this request on newest master

**Comment by TheSiege** [comment]
compiles and runs on
ubuntu 12.04
fedora 17

**Pull request merged**
