### PR TITLE
install script DO NOT MERGE

### PR DESCRIPTION
**Pull request by matthiaskrgr**
DO NOT MERGE
this is a test, I'm trying to implement the features suggested here: https://github.com/lodle/Desurium/pull/462#issuecomment-13395573

but I want to make sure that this works for other people as well.

input:
./build_desura.sh --compile desura -j 2 --rebuild cef check --help nope

output should be 
Make sure to run sudo ./install-deps.sh before compiling!

compile desura -j 2 
rebuild cef check 
help nope

when I only use --help at the end, I get "help help help" on last line, I have to fix this.

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@karolherbst  :)

**Comment by karolherbst** [comment]
I think the best would be to parse the arguments first and then do the actions

and what should happen with this:

```
./build_desura.sh --compile desura -j 2 --rebuild desura check --help nope
```

**Comment by matthiaskrgr** [comment]
I just wanted to know if the code above works at all!

**Comment by karolherbst** [comment]
I think this is just too complicated

**Comment by matthiaskrgr** [comment]
I'll try anyway :>

**Pull request closed without merging**
