### PR TITLE
some win32 stuff

### PR DESCRIPTION
**Pull request by karolherbst**
with this changes, desurium can be compiled on Windows with mingw and msvc. Currently CEF won't compile and we don't have a proper non MFC bootloader.

I want to merge this stuff, becaus I won't work on this for a while (0.8 have much more prio)

### CODE REVIEW

**Comment by TheSiege** [comment]
doesn't breake compilation on my gentoo system; so go ahead

**Comment by karolherbst** [comment]
I have to rebase this; "This pull request cannot be automatically merged."

**Comment by karolherbst** [comment]
rebased

**Comment by matthiaskrgr** [comment]
[ 65%] Built target fetch_cef
[ 68%] Performing copy_files step for 'cef'
[ 70%] Creating directories for 'cef'
[ 73%] No download step for 'cef'
[ 75%] Performing config_cef step for 'cef'
  File "tools/gclient_hook.py", line 14
    except ImportError, e:
                      ^
SyntaxError: invalid syntax
make[2]: **\* [cef-prefix/src/cef-stamp/cef-config_cef] Error 1
make[1]: **\* [CMakeFiles/cef.dir/all] Error 2
make: **\* [all] Error 2

**Comment by karolherbst** [comment]
@matthiaskrgr fixed error

**Comment by matthiaskrgr** [comment]
[  4%] Built target curl
[  6%] Built target fetch_cef
[  6%] Performing download step (download, verify and extract) for 'wxWidget-2-9'
-- downloading...
     src='ftp://ftp.wxwidgets.org/pub/2.9.3/wxWidgets-2.9.3.tar.bz2'
     dst='/home/matthias/vcs/github/desurium_fork_bkp/build/wxWidget-2-9-prefix/src/wxWidgets-2.9.3.tar.bz2'
     timeout='none'
-- [download 0% complete]

somehow the file is not being downloaded.
It has been at 0% for 5 minutes now.

**Comment by karolherbst** [comment]
the server is very slow, that is normal behaviour, please use the cmake option instead

**Comment by matthiaskrgr** [comment]
I really suggest we use the sourceforge download.

note to my: append   -DWXWIDGET_URL="http://garr.dl.sourceforge.net/project/wxwindows/2.9.3/wxWidgets-2.9.3.tar.bz2"  to cmake cmd

**Comment by matthiaskrgr** [comment]
ok, the download issue has been fixed.
this needs rebase or master merged now :P

**Comment by karolherbst** [comment]
rebased

**Comment by karolherbst** [comment]
I want to merge this very soon, so it would be easier to work on a win32 build on top of lodle/master

**Comment by karolherbst** [comment]
rebased on current master

**Comment by matthiaskrgr** [comment]
works here.

**Pull request merged**
