### PR TITLE
cmake and source changes for desurium windows build

### LINKED ISSUE #106: cmake: build on windows
few things:

utilcore
executables
install paths.

### LINKED ISSUE #329: User avatar not respecting proper alpha
The client seems to only support 1-bit alpha in avatars in the top left of the window (next to the menu button). It ignores semi-transparent pixels and applies full alpha to them.

### LINKED ISSUE #583: util/OS: some functions not implemented on windows
in the file https://github.com/desura/Desurium/blob/44c813f30a6d14c2681fd38d486634d070cae157/src/static/util/code/UtilOs.cpp are some function only implemented on Linux.
- [x] getCachePath(std::wstring extra)
- [x] getAppInstallPath(std::wstring extra)

### PR DESCRIPTION
**Pull request by karolherbst**
this pull request add all stuff needed to build desurium on windows systems

There are still some issues left with the CEF build:
- The DirectX9 include path has to be added manually, but we check already for the DirectX SDK
- one perl script is aborting with some internel windows error (while opening shared libraries or something), adding a "select(undef, undef, undef, 0.2)" before the call helped for me.

Except of this issues, desurium seems to run just fine. I've tested installing/running games, browser through the store and view flash videos. H.264 won't work with the chromium 15 code base, because it does not support building ffmpeg and we can only download ffmpeg dlls without prop. codec support.

this pull request fixes #106 and fixes #583. It also fixes #329 for windows, it was already for Linux.

### CODE REVIEW

**Comment by Jookia** [comment]
Does this work on Linux?

**Comment by karolherbst** [comment]
travis-ci doesn't find any compile errors and I tried it out on Linux once (before the commit clean up).

I am pretty sure it will work, because most of the changes are in win32 only parts.

But here is a list of commits, which are effecting Linux parts, too.
- https://github.com/karolherbst/Desurium/commit/3329e40f5dad9a241f7598596da258e1f7a76e7d
- https://github.com/karolherbst/Desurium/commit/277bd7df4751a0322198f94e79fbe6181dd4f649
- https://github.com/karolherbst/Desurium/commit/1f519e36929442fe57cf0d192235ca4ae347a71f
- https://github.com/karolherbst/Desurium/commit/4b1d52b654ebf7b3d3d55b726cf385698a2adc9f
- https://github.com/karolherbst/Desurium/commit/df5998979f3bc81bb73accd6520cbb63dbb7c44b
- https://github.com/karolherbst/Desurium/commit/c2fd3174864a0cda666949b7a7a2d72a3343021c

**Comment by karolherbst** [comment]
I will do some deep testing anyway, I just wanted to make this request, so others can try it out and test, too

**Comment by karolherbst** [comment]
okay, got one compile error in cef:

```
cef/libcef/webview_host.cc: At global scope:
cef/libcef/webview_host.cc:7:1: error: prototype for ‘WebViewHost::WebViewHost(BrowserWebViewDelegate*)’ does not match any in class ‘WebViewHost’
 WebViewHost::WebViewHost(BrowserWebViewDelegate* delegate)
 ^
In file included from cef/libcef/webview_host.cc:5:0:
cef/libcef/webview_host.h:26:7: error: candidates are: WebViewHost::WebViewHost(const WebViewHost&)
 class WebViewHost : public WebWidgetHost {
       ^
cef/libcef/webview_host.h:26:7: error:                 WebViewHost::WebViewHost()
```

**Comment by karolherbst** [comment]
I fixed the commit and it should work now on both Linux and Windows

**Comment by Jookia** [comment]
I'm going to merge, even if it breaks things as I think it just needs to be gotten over with. Also documentation needs to be worked on.

**Comment by karolherbst** [comment]
The windows cef build is a bit borked, but for developing a pre compiled cef dll is more than enough. It isn't impossible to build cef on windows, there are only some modifications needed for it.

Anyway, now we can start to seperate cef from desura_cef and split the repository.

**Pull request merged**
