### PR TITLE
Wx detect

### PR DESCRIPTION
**Pull request by makson96**
If someone want to use system wxWidgets with Desurium he would probably have default 2.8 version and 2.9.3 as a choice. But if 2.9.3 is not default, than even if wxWidgets_CONFIG_EXECUTABLE and wxWidgets_wxrc_EXECUTABLE is set, the test will fail because those options are not passed to the test. This pull is fixing the issue.

### CODE REVIEW

**Comment by karolherbst** [comment]
seems okay, I will looker deeper into it later

**Comment by TheSiege** [comment]
compiles fine; doesn't break things (tried ebuild; build_desura.sh and a few cmake options)

**Comment by karolherbst** [comment]
We could change the ebuild a bit with this changes

**Comment by TheSiege** [comment]
I am pretty sure wx.eclass handles that in gentoo ...

**Comment by karolherbst** [comment]
makes sense

**Comment by karolherbst** [comment]
works for me

**Pull request merged**
