### PR TITLE
implement full debug builds in cmake for linux and some #130 stuff

### PR DESCRIPTION
**Pull request by karolherbst**

### CODE REVIEW

**Comment by Jookia** [comment]
I find this redundant as most external libs aren't debug since they're installed by package managers.

**Comment by karolherbst** [comment]
but on windows we must to have an option in cmake to build external debug libraries. At least for boost and wxWidgets. So I think a better way to do this would be the usage of an option like: DEBUG_EXTERNEL.

As for gentoo there are a debug option for most of the libraries to build both: release and debug libs.

**Comment by Jookia** [comment]
Hmm.. DEBUG and DEBUG_EXTERNAL , two separate objects. I really like the idea.

**Comment by Jookia** [comment]
Reviewing the patch, you removed the ability to use a custom branding, and changed 'Desura' to 'Desurium'. :l

**Comment by karolherbst** [comment]
you're right, didn't thought about that.

**Pull request merged**
