### PR TITLE
util: don't sanitize '..' to '.'

### LINKED ISSUE #239: Styling Issue - Scrollbar colours
This should be a trivial bug fix, make the scrollbars the same colour on all sections, looks odd on the play section to have a black scrollbar than all other tabs grey?

Just a styling issue.

### PR DESCRIPTION
**Pull request by karolherbst**
and some tests are added

also fixes #239

NOTE: this is a candidate for the stable branch

### CODE REVIEW

**Comment by TheSiege** [comment]
fixes issue; works

**Comment by lodle** [comment]
The whole reason that .. are removed to stop bad url's accessing paths that they shouldnt be allowed to

**Comment by karolherbst** [comment]
This makes sense, but isn't sandboxing a better solution for that?

**Comment by lodle** [comment]
well, given unlimited time, yes but desura does load content from 3rd parties.

**Comment by karolherbst** [comment]
I meant only sandboxing the internal browser. But in general, if we want to be FHS complianet, we have to respect that, that we have to access files, which aren't subfolders if the "binary folder" of desura.

I could also eliminate all ".." in the theme path folder, where this path is coming from.

**Comment by lodle** [comment]
Go for it then, im offering insight as to why it was like that, if needs change, then the code has to change.

**Comment by karolherbst** [comment]
I will create an issue because of sandboxing.

**Pull request merged**
