### PR TITLE
System wxWidgets

### PR DESCRIPTION
**Pull request by karolherbst**
these changes will allow us to use a system wide installed wxWidgets.

works for:
- karolherbst

### CODE REVIEW

**Comment by TheSiege** [comment]
works really well for me; gentoo gcc-4.7.1
had it running for some time; provides a generally more responsive interface for me

**Comment by makson96** [comment]
Well it needs wxWidgets 2.9. The latest version even in Ubuntu 12.10 alpha and Debian Sid repositories is 2.8. So it is useless for those distributions at the moment. What is more, even if I try this branch with:
"cmake -DCMAKE_INSTALL_PREFIX=../install -D32BIT_SUPPORT=ON -DFORCE_SYS_DEPS=OFF .."
it will try to use system wxWidgets instead of building it's own.

**Comment by ssokolow** [comment]
@makson96 wxWidgets uses the same even/odd stable/unstable versioning as minor kernel version numbers, so we probably won't see Ubuntu and Debian update their copy from 2.8.x until wxWidgets releases 2.10.0.

I remember 2.7 being masked back when I was on Gentoo and 2.8 hadn't yet been released.

**Comment by karolherbst** [comment]
mhh okay, because I won't be home today I will fix your issues the next days. I hope I will finish this on Friday

**Comment by karolherbst** [comment]
another question is: do we need wxWidget 2.9? Maybe source files, which aren't used by anoyone depends on 2.9. I will take a further look here.

**Comment by karolherbst** [comment]
okay, no makson96, this is the right behaviour of this option, because it only force the use of sys libs (to throw errors if there aren't find).

FORCE_SYS_DEPS=OFF just means: if you find a sys lib use this, if not, build it.

There is just an error with the version of wxWidgets. Cmake should check for 2.9 but it doesn't

**Comment by makson96** [comment]
I don't get this switch.
If someone does have system lib, then he can not chose to use it or build it, but if someone doesn't have system lib there is no point of the switch because he must build it's own anyway.

**Comment by karolherbst** [comment]
this is usefull when you really don't want to build libs on your own (like in portage or to reduce compile time). Further there is no reason why you should build a lib on your own, if it exists on your system.

**Comment by TheSiege** [comment]
https://github.com/lodle/Desurium/pull/265/files#L0R123
is depreceated as we don't patch wxWidgets anymore

**Comment by karolherbst** [comment]
I will merge this request on Monday if no other errors appear

**Comment by karolherbst** [comment]
we have to fix #276 first so this pull request will not be merged today or Tuesday

**Comment by karolherbst** [comment]
I've ported to wxWidgets-2.9.4, but there are some performance issues and GUI bugs in desurium. I will try to fix them tomorrow.

In fact that means, that this pull request will be delayed until the next weekend

**Comment by TheSiege** [comment]
the performance did not regress for me and the GUI bug is that the windows empty and I have to switch to other windows to  load them again.

**Comment by karolherbst** [comment]
what is not good anyways

**Comment by karolherbst** [comment]
rebased on newest master (boost_fs3 fixes are included)

**Comment by makson96** [comment]
Hi,
I have issue with this branch. I have compiled wxwidgets 2.9.3 in my launchpad ppa:
https://launchpad.net/~makson96/+archive/desurium
And then tried to use it for desurium compilation. It detects wxwidgets but instead of using it it tries to download and compile it.
Buildlog:
https://launchpadlibrarian.net/111631828/buildlog_ubuntu-precise-i386.desurium_1%3A2012.08.01-makson1~ppa1_FAILEDTOBUILD.txt.gz
line 1411 detects wxwidgets
line 1803 try to download wxwidgets (build server do not allow such a behavior)
No compilation options were given to cmake command.

**Comment by TheSiege** [comment]
I'd advise everyone not to use wxgtk 2.9.4 is makes the desurium client unusable at the moment as it causes crashes whenever you want to uninstall a game or verify it

**Comment by karolherbst** [comment]
okay, we should find out what the main problem is, maybe the wxWidgets guys are able to do a good guess, so someone should write to them.

**Comment by karolherbst** [comment]
rebased on newest master

**Comment by TheSiege** [comment]
this is what happenes when I go to the games tab the first time:
https://imageshack.us/content_round.php?page=done&l=img51/1954/desu1.jpg
changing the tab ones helps
when I verify a game this happenes:

```
$XDG_CONFIG_HOME not set, falling back to $HOME/.config.
$XDG_CACHE_HOME not set, falling back to $HOME/.cache.
(17709, son of 17704) /var/tmp/portage/games-util/desurium-99999/work/desurium-99999/src/executable/bootloader_lin/code/DesuraMain.cpp:154 - #########################################
(17709, son of 17704) /var/tmp/portage/games-util/desurium-99999/work/desurium-99999/src/executable/bootloader_lin/code/DesuraMain.cpp:155 - #               DEBUG BUILD             #
(17709, son of 17704) /var/tmp/portage/games-util/desurium-99999/work/desurium-99999/src/executable/bootloader_lin/code/DesuraMain.cpp:156 - #########################################
(17709, son of 17704) /var/tmp/portage/games-util/desurium-99999/work/desurium-99999/src/executable/bootloader_lin/code/UtilFile.cpp:67 - ChangeToAppDir
(17709, son of 17704) /var/tmp/portage/games-util/desurium-99999/work/desurium-99999/src/executable/bootloader_lin/code/UtilFile.cpp:24 - GetAppPath
(17709, son of 17704) /var/tmp/portage/games-util/desurium-99999/work/desurium-99999/src/executable/bootloader_lin/code/UtilFile.cpp:69 - /usr/games/desurium
MCFCore Logging Started.
WebCore Logging Started.
UserCore Logging Started.
--------------------------------------------------
Desura Version          : 1.0.0.0
MCFCore Version         : 0.0.0.1
UICore Version          : 0.0.0.1
UserCore Version        : 0.0.0.1
WebCore Version         : 0.0.0.1
--------------------------------------------------
Logging has started


Loaded Language file: german
(17710, son of 17709) /var/tmp/portage/games-util/desurium-99999/work/desurium-99999/src/shared/uicore/code/UICoreMain.cpp:87 - /home/anagromataf/.desura/cache/socket
DS: Version: 0.0.0.1
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
unnamed app(17710) KMimeTypePrivate::ensureXmlDataLoaded: Missing <comment> field in "application/x-msdownload.xml" 
unnamed app(17710) KMimeTypePrivate::ensureXmlDataLoaded: Missing <comment> field in "application/x-wine-extension-asa.xml" 
unnamed app(17710) KMimeTypePrivate::ensureXmlDataLoaded: Missing <comment> field in "application/x-wine-extension-bsp.xml" 
unnamed app(17710) KMimeTypePrivate::ensureXmlDataLoaded: Missing <comment> field in "application/x-wine-extension-cdx.xml" 
unnamed app(17710) KMimeTypePrivate::ensureXmlDataLoaded: Missing <comment> field in "application/x-wine-extension-dem.xml" 
unnamed app(17710) KMimeTypePrivate::ensureXmlDataLoaded: Missing <comment> field in "application/x-wine-extension-key.xml" 
unnamed app(17710) KMimeTypePrivate::ensureXmlDataLoaded: Missing <comment> field in "text/x-component.xml" 
/var/tmp/portage/x11-libs/wxGTK-2.9.4.1/work/wxPython-src-2.9.4.0/src/gtk/bitmap.cpp(860): assert "IsOk()" failed in GetHeight(): invalid bitmap
wx Assert: /var/tmp/portage/x11-libs/wxGTK-2.9.4.1/work/wxPython-src-2.9.4.0/src/gtk/bitmap.cpp(860): assert "IsOk()" failed in GetHeight(): invalid bitmap
/var/tmp/portage/x11-libs/wxGTK-2.9.4.1/work/wxPython-src-2.9.4.0/src/gtk/bitmap.cpp(867): assert "IsOk()" failed in GetWidth(): invalid bitmap
```

**Comment by karolherbst** [comment]
nice one. This could be the error. Now someone hast to figure out where the calls are

**Comment by lodle** [comment]
looks like the child window cef attaches to no longer exists. This was a pain to get working in the first place

**Comment by Mailaender** [comment]
It is true that 2.8.X is the latest stable version even in upcoming distributions. Still packaging wxWidgets 2.9.3 independently saves a lot of build time when updating Desurium. Currently it takes 1h to build Desurium on https://build.opensuse.org/ Also this violates packaging rules as said at https://bugs.gentoo.org/show_bug.cgi?id=395837

**Comment by karolherbst** [comment]
Mailaender the problem isn't wxWidgets, it is CEF, which takes a lot of time

**Comment by karolherbst** [comment]
rebased on current master, because of boost fixes

**Comment by karolherbst** [comment]
I want to merge this on Tuesday

**Comment by karolherbst** [comment]
I made some changes and rebased it because of ebuild changes. please test. merge will be delayed to Friday

**Comment by Mailaender** [comment]
Does not work for me at https://build.opensuse.org/package/show?package=Desurium&project=home%3AMailaender

```
[  165s] [329/329] installing wxWidgets-devel-2.9.3-43.1
```

```
[  195s] -- Found wxWidgets: TRUE (Required is at least version "2.9")
[  201s] CMake Error at CMakeLists.txt:142 (message):
[  201s]   no wxWidget-2.9.3 found
```

**Comment by karolherbst** [comment]
@Mailaender could you tell me the values of wxMAJOR_VERSION, wxMINOR_VERSION and wxRELEASE_NUMBER in <wx/version.h> ?

And are you able to try out this little cmake project? https://github.com/lodle/Desurium/tree/system_wx/cmake/tests/wxWidget_2.9_test

I don't now what the error could be, so we have to try things out.

**Comment by Mailaender** [comment]
I tried the cmake project on my local machine with 2.9.3 installed http://paste.opensuse.org/view/simple/91079339 and don't know where I can see the wx*_VERSION.

**Comment by karolherbst** [comment]
wx*_VERSION are defined in &lt;wx/config.h&gt; ... because of html tags and stuff, this wasn't shown. Further you should try to compile this little test, because it is a compile test ;)

**Comment by Mailaender** [comment]
```
matthias@mPad-X61s:~/Dokumente> wx-config --version-full
2.9.3.0
```

**Comment by Mailaender** [comment]
Does not compile:

```
Scanning dependencies of target wxWidget_2_9_test
[100%] Building CXX object CMakeFiles/wxWidget_2_9_test.dir/wxWidget_2.9_test.cpp.o
In file included from /usr/include/wx-2.9/wx/stream.h:22:0,
                 from /usr/include/wx-2.9/wx/image.h:24,
                 from /usr/include/wx-2.9/wx/bitmap.h:22,
                 from /home/matthias/Downloads/lodle-Desurium-2db2aa8/cmake/tests/wxWidget_2.9_test/wxWidget_2.9_test.cpp:1:
/usr/include/wx-2.9/wx/filefn.h:518:9: error: zero width for bit-field ‘wxAssert_519::BadFileSizeType’
make[2]: *** [CMakeFiles/wxWidget_2_9_test.dir/wxWidget_2.9_test.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/wxWidget_2_9_test.dir/all] Fehler 2
make: *** [all] Fehler 2
```

**Comment by Mailaender** [comment]
I found it in /usr/include/wx-2.9/wx/version.h:

```
#define wxMAJOR_VERSION      2
#define wxMINOR_VERSION      9
#define wxRELEASE_NUMBER     3
#define wxSUBRELEASE_NUMBER  0
#define wxVERSION_STRING   wxT("wxWidgets 2.9.3")
```

**Comment by karolherbst** [comment]
@Mailaender should be fixed now

**Comment by Mailaender** [comment]
New issue at https://build.opensuse.org/package/live_build_log?arch=i586&package=Desurium&project=home%3AMailaender&repository=openSUSE_12.1

```
[ 1110s] /home/abuild/rpmbuild/BUILD/Desurium-1346925951/src/include/wx_controls/wxEventDelegate.h:45:118: error: no matching function for call to 'MenuSeperator::MenuSeperator(wxWindow*&, const wxString&, const wxSize&)'
```

http://paste.opensuse.org/view/simple/56755647

**Comment by karolherbst** [comment]
would you like to try out this patch? I don't know if this would break up other things, because I can't test a compile with it at the moment.

``` patch
diff --git a/src/include/wx_controls/wxEventDelegate.h b/src/include/wx_controls/wxEventDelegate.h
index aba6b93..3af9cd3 100644
--- a/src/include/wx_controls/wxEventDelegate.h
+++ b/src/include/wx_controls/wxEventDelegate.h
@@ -42,7 +42,7 @@ public:
        m_pMainCustFrame = NULL;
    }

-   wxEventDelegate(wxWindow *parent, const wxString& label, const wxSize& size = wxDefaultSize) : T(parent, label, size)
+   wxEventDelegate(wxWindow *parent, const wxString& label, const wxSize& size = wxDefaultSize) : T(parent, label.c_str(), size)
    {
        m_pMainCustFrame = NULL;
    }

```

**Comment by Mailaender** [comment]
I am not very confident with patching.

```
+ cd Desurium-1346925951
+ /bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ echo 'Patch #0 (wxEventDelegate.patch):'
Patch #0 (wxEventDelegate.patch):
/bin/cat /home/abuild/rpmbuild/SOURCES/wxEventDelegate.patch
/usr/bin/patch -s -p0 --fuzz=0
The text leading up to this was:
--------------------------
|diff --git a/src/include/wx_controls/wxEventDelegate.h b/src/include/wx_controls/wxEventDelegate.h
|index aba6b93..3af9cd3 100644
|--- a/src/include/wx_controls/wxEventDelegate.h
|+++ b/src/include/wx_controls/wxEventDelegate.h
--------------------------
File to patch: 
Skip this patch? [y] 
1 out of 1 hunk ignored
error: Bad exit status from /var/tmp/rpm-tmp.X0gHW9 (%prep)
```

**Comment by karolherbst** [comment]
patch -p1 < wxEventDelegate.patch
or
patch -p1 -i wxEventDelegate.patch
or
cat wxEventDelegate.patch | patch -p1

but i prefer the first one

**Comment by karolherbst** [comment]
@Mailaender please use the old methoed and this patch:

``` patch
diff --git src/include/wx_controls/wxEventDelegate.h src/include/wx_controls/wxEventDelegate.h
index aba6b93..3af9cd3 100644
--- src/include/wx_controls/wxEventDelegate.h
+++ src/include/wx_controls/wxEventDelegate.h
@@ -42,7 +42,7 @@ public:
        m_pMainCustFrame = NULL;
    }

-   wxEventDelegate(wxWindow *parent, const wxString& label, const wxSize& size = wxDefaultSize) : T(parent, label, size)
+   wxEventDelegate(wxWindow *parent, const wxString& label, const wxSize& size = wxDefaultSize) : T(parent, label.c_str(), size)
    {
        m_pMainCustFrame = NULL;
    }

```

**Comment by Mailaender** [comment]
Still won't work. See http://en.opensuse.org/openSUSE:Build_Service_Tutorial#Patches for the guidelines those RPM macros need.

**Comment by karolherbst** [comment]
I've created a branch:
https://github.com/karolherbst/Desurium/tree/system_wx_patched

**Comment by Mailaender** [comment]
Seems to fix the issue. The build will however still not finish: https://build.opensuse.org/package/live_build_log?arch=i586&package=Desurium&project=home%3AMailaender&repository=openSUSE_12.1 It stops after cef and I don't see the error.

**Comment by karolherbst** [comment]
I found it:
[ 2881s] /home/abuild/rpmbuild/BUILD/Desurium-1347021366/src/shared/uicore/code/MainApp.cpp: In member function 'void MainApp::Init(int, wxCmdLineArgsArray&)':
[ 2881s] /home/abuild/rpmbuild/BUILD/Desurium-1347021366/src/shared/uicore/code/MainApp.cpp:278:51: error: invalid cast from type 'wxString' to type 'const char*'

**Comment by karolherbst** [comment]
@Mailaender I've updated the lodle system_wx branch. Any errors left?

**Comment by Mailaender** [comment]
It builds successfully. The libwx_gtk2u_desura-2.9.so.3 is gone now.

**Comment by karolherbst** [comment]
merge on Sunday, waiting for other issues

**Pull request merged**
