### PR TITLE
updated readme and install-deps

### PR DESCRIPTION
**Pull request by yurikoles**
Removed dependecies list from readme, now it's refer to install-deps.sh, added build.sh

### CODE REVIEW

**Comment by yurikoles** [comment]
I think commands that user need to invoke before build except cloning git should be made ​​outside README

**Comment by yurikoles** [comment]
I rechecked, last call ./build.sh is in directory build_lin, not in root of source tree.

**Comment by Jookia** [comment]
Ah. This patch is great, exactly what I've been looking for. Though I don't see a justification for the Git cloning, seeing as the person may of obtained the source outside of Git, or have already used Git to get the source.

**Comment by Jookia** [comment]
What I'm saying is, could you please remove the Git part?

**Pull request merged**
