### PR TITLE
wx_controls: remove private API usage

### PR DESCRIPTION
**Pull request by karolherbst**
we should not use private fields or private APIs in general.

### CODE REVIEW

**Comment by TheSiege** [comment]
still compiles on my gentoo

**Comment by karolherbst** [comment]
I want to do some VC checks before merging this, but I won't have enough time for it until Tuesday

**Comment by Jookia** [comment]
This seems like a fantastic addition.

**Comment by karolherbst** [comment]
seems to compile fine on msvc100 (well, I was able to compile the whole project on msvc100, except cef and every MFC dependent part)

**Pull request merged**
