### PR TITLE
bug417 fix

### LINKED ISSUE #417: cef: can't play flash videos
desurium don't have the source to view flash videos from the official desura sources.

We need them

### PR DESCRIPTION
**Pull request by karolherbst**
with these changes desurium is able to watch flash movies. It will uses the system wide installed libflashplayer.so on Linux from the nsbrowser plugin directory.

In addition to that, I removed all these libs/ bin/ and _32, _64 stuff used by the official desura binary. Desurium will look in the RUNTIME_LIB_DIR for libdesura_flashwrapper.so and desura_flashhost (As long as LD_LIBRARY_PATH and PATH were set to it, like in the run.sh script)

fixes #417

NOTES:
- this serires is a candidate for the stable branch
- CEF needs to rebuild for that

### CODE REVIEW

**Comment by karolherbst** [comment]
xlib xt dependency is missing in the ebuild. I will fix this tomorrow

**Comment by TheSiege** [comment]
```
In file included from /home/anagromataf/github/Desurium/third_party/npwrapper/src/common/debug.c:21:0:
/home/anagromataf/github/Desurium/third_party/npwrapper/src/common/sysdeps.h:26:2: error: #error "Your compiler is not ISO. Get a real one."
/home/anagromataf/github/Desurium/third_party/npwrapper/src/common/debug.c: In function 'npw_print_indent':
/home/anagromataf/github/Desurium/third_party/npwrapper/src/common/debug.c:146:3: error: 'for' loop initial declarations are only allowed in C99 mode
/home/anagromataf/github/Desurium/third_party/npwrapper/src/common/debug.c:146:3: note: use option -std=c99 or -std=gnu99 to compile your code
make[2]: *** [third_party/npwrapper/CMakeFiles/desura_flashhost.dir/src/common/debug.c.o] Error 1
make[1]: *** [third_party/npwrapper/CMakeFiles/desura_flashhost.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by matthiaskrgr** [comment]
I assume I need to add adobe-flash as dep to the PKGBUILDs once this gets merged.

The binary is in
yaourt -Ql flashplugin | grep libfl
flashplugin /usr/lib/mozilla/plugins/libflashplayer.so

**Comment by matthiaskrgr** [comment]
Yep I am getting this error, too

[  8%] Built target sqlite3x
[  9%] Building C object third_party/npwrapper/CMakeFiles/desura_flashhost.dir/src/common/debug.c.o
In file included from /home/matthias/vcs/github/desurium_fork_bkp/third_party/npwrapper/src/common/debug.c:21:0:
/home/matthias/vcs/github/desurium_fork_bkp/third_party/npwrapper/src/common/sysdeps.h:26:2: error: #error "Your compiler is not ISO. Get a real one."
/home/matthias/vcs/github/desurium_fork_bkp/third_party/npwrapper/src/common/debug.c: In function ‘npw_print_indent’:
/home/matthias/vcs/github/desurium_fork_bkp/third_party/npwrapper/src/common/debug.c:146:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
/home/matthias/vcs/github/desurium_fork_bkp/third_party/npwrapper/src/common/debug.c:146:3: note: use option -std=c99 or -std=gnu99 to compile your code
make[2]: **\* [third_party/npwrapper/CMakeFiles/desura_flashhost.dir/src/common/debug.c.o] Error 1
make[1]: **\* [third_party/npwrapper/CMakeFiles/desura_flashhost.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....

**Comment by matthiaskrgr** [comment]
https://bugs.launchpad.net/ubuntu/+source/nspluginwrapper/+bug/805222

**Comment by karolherbst** [comment]
okay, I forgot to add this -std=c99 in cmake. I ran into this error once.

**Comment by karolherbst** [comment]
mhh this flashplayer path problem can be big in the future.

I am thinking about adding a new option to cmake (FLASH_PLUGIN_PATH). I would just add this to the LD_LIBRARY_PATH and eliminate the fixed path to libflashplayer.so. A relative path will be searched in LD_LIBRARY_PATH I think (but I am not sure with this).

**Comment by TheSiege** [comment]
compiles as expected, works as expected; please pull ASAP people wait for this

**Pull request merged**
