### PR TITLE
Gentoo bug fixes

### PR DESCRIPTION
**Pull request by karolherbst**
this should all bugs on gentoo systems (found by @TheSiege)

### CODE REVIEW

**Comment by TheSiege** [comment]
result:

```
The program 'npviewer' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadDrawable (invalid Pixmap or Window parameter)'.
  (Details: serial 116 error_code 9 request_code 14 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
*** NSPlugin Wrapper *** ERROR: NPP_HandleEvent() wait for reply: Connection closed
*** NSPlugin Wrapper *** WARNING:(/var/tmp/portage/games-util/desurium-9999/work/desurium-9999/third_party/npwrapper/src/wrapper/npw-wrapper.c:2902):invoke_NPP_HandleEvent: assertion failed: (rpc_method_invoke_possible(plugin->connection))
*** NSPlugin Wrapper *** WARNING:(/var/tmp/portage/games-util/desurium-9999/work/desurium-9999/third_party/npwrapper/src/wrapper/npw-wrapper.c:2902):invoke_NPP_HandleEvent: assertion failed: (rpc_method_invoke_possible(plugin->connection))
*** NSPlugin Wrapper *** WARNING:(/var/tmp/portage/games-util/desurium-9999/work/desurium-9999/third_party/npwrapper/src/wrapper/npw-wrapper.c:2273):invoke_NPP_SetWindow: assertion failed: (rpc_method_invoke_possible(plugin->connection))
```

**Comment by TheSiege** [comment]
as requested in a minimal x enviroment error still happens

**Comment by TheSiege** [comment]
this is a linking issue I think;

```
compiled with build_desura.sh         compiled by portage
video works                                    video doesn't work                    without this pull request
video doesn't work                          video doesn't work                    with pull request
```

the latter error is the same error presented above
without the pull request desura compiled by portage complains about missing symbols

**Comment by matthiaskrgr** [comment]
compiles on arch linux

**Comment by matthiaskrgr** [comment]
but breaks videos

**\* NSPlugin Wrapper **\* WARNING:(/home/matthias/vcs/github/desurium_fork_bkp/third_party/npwrapper/src/wrapper/npw-wrapper.c:2902):invoke_NPP_HandleEvent: assertion failed: (rpc_method_invoke_possible(plugin->connection))
 en mass

**Comment by NothingMuchHereToSay** [comment]
Doesn't compile on Debian Wheezy:

```
Linking C executable desura_flashhost
/usr/bin/ld: CMakeFiles/desura_flashhost.dir/src/common/rpc.c.o: undefined reference to symbol 'pthread_cancel@@GLIBC_2.2.5'
/usr/bin/ld: note: 'pthread_cancel@@GLIBC_2.2.5' is defined in DSO /lib/x86_64-linux-gnu/libpthread.so.0 so try adding it to the linker command line
/lib/x86_64-linux-gnu/libpthread.so.0: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make[2]: *** [third_party/npwrapper/desura_flashhost] Error 1
make[1]: *** [third_party/npwrapper/CMakeFiles/desura_flashhost.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by karolherbst** [comment]
could you run this with NPW_DEBUG=1 NPW_LOG=nspluginwrapper.log and post this log file?

**Comment by karolherbst** [comment]
is this patch helping with the ebuild?

``` patch
diff --git a/distro/gentoo/portage/games-util/desurium/desurium-9999.ebuild b/distro/gentoo/portage/games-util/desurium/desurium-9999.ebuild
index e338524..141406f 100644
--- a/distro/gentoo/portage/games-util/desurium/desurium-9999.ebuild
+++ b/distro/gentoo/portage/games-util/desurium/desurium-9999.ebuild
@@ -32,7 +32,7 @@
        ${WX_URI}
    )"

-inherit cmake-utils eutils ${GIT_ECLASS} gnome2-utils ${WX_ECLASS} games toolchain-funcs
+inherit cmake-utils eutils flag-o-matic ${GIT_ECLASS} gnome2-utils ${WX_ECLASS} games toolchain-funcs

 DESCRIPTION="Free software version of Desura game client"
 HOMEPAGE="https://github.com/lodle/Desurium"
@@ -147,6 +147,9 @@
 }

 src_configure() {
+   # on some systems -Wl,--as-needed breaks the flashplayer
+   filter-ldflags -Wl,--as-needed
+   
    # -DWITH_ARES=FALSE will use system curl, because we force curl[ares] to have ares support
    local mycmakeargs=(
        -DWITH_ARES=FALSE
```

**Comment by TheSiege** [comment]
as expected filtering --as-need out provides a working bin

**Comment by TheSiege** [comment]
works; pull

**Pull request merged**
