### PR TITLE
Update install-deps.sh

### PR DESCRIPTION
**Pull request by makson96**

### CODE REVIEW

**Comment by karolherbst** [comment]
I will try to test and merge it the next week

**Comment by karolherbst** [comment]
shit I forgot this stuff, I will have time today or at the weekend maybe.

**Comment by makson96** [comment]
OK. I am waiting for any comments.

**Comment by karolherbst** [comment]
I think this pull request will be broken on debian and pre ubuntu-12.04 lts machines, but I will test this first

**Comment by makson96** [comment]
Why?
Both Debian and Ubuntu have gcc-multilib and libc6-dev-i386 packages in all supported versions.

**Comment by karolherbst** [comment]
mhh okay, I thought there were some changes in the newest ubuntu release, but okay

**Pull request merged**
