### PR TITLE
BuildCEF

### LINKED ISSUE #107: CEF is awesome, big and depends on own build system
At the moment I try to build CEF and cougette with cmake, but this is not so easy as I thought. My idea is to invoke the known cef_create_projects script via cmake to get everything build.
It seems that cef and courgette were the main reasons to choose gyp.

Jookia:
I say we worry about CEF last. I think your idea is as correct as it can be. Check out via CMake, yadayadayada, build it using gyp. Please note that gyp requires Python 2.

for reference the tree with old build files:
https://github.com/lodle/Desurium/tree/c21c857ac21957e1785aa60cac9439e8dc3f2ab6

ebuild in gentoo to build chromium:
http://gentoo-overlays.zugaina.org/gentoo/portage/www-client/chromium/chromium-18.0.1025.142.ebuild

### PR DESCRIPTION
**Pull request by karolherbst**
steps:
1. download depot_tools
2. fetch chromium
3. fetch cef
4. run script in cef clone
5. build it
6. set cmake vars for include and lib

status: 6/6 done (Linux)

discussion and improvements here

fixes #107

### CODE REVIEW

**Comment by TheSiege** [comment]
nice links
http://code.google.com/p/chromiumembedded/source/browse/trunk/CHROMIUM_BUILD_COMPATIBILITY.txt
https://code.google.com/p/chromiumembedded/
http://dev.chromium.org/developers/how-tos/get-the-code

**Comment by Jookia** [comment]
HUZZAH

**Comment by karolherbst** [comment]
todo: set python to version 2 for cef

**Comment by karolherbst** [comment]
I hope compiling CEF should work now for everyone

**Comment by karolherbst** [comment]
so it should work with python3 as default python now. cef build step is untested, wait for review

**Comment by Jookia** [comment]
Requires this patch: https://projects.archlinux.org/svntogit/packages.git/tree/trunk/chromium-gcc47.patch?h=packages/chromium

**Pull request merged**
