### PR TITLE
ebuild update for gentoo

### PR DESCRIPTION
**Pull request by karolherbst**
things not working:
- icon displayed in appplication menu
- using run.sh

### CODE REVIEW

**Comment by Jookia** [comment]
Don't need launch-desura.sh. Just symlink to the install dir's run.sh

**Comment by karolherbst** [comment]
symlinking run.sh isn't working for me, because I can't run it from wherever I want.

**Comment by Jookia** [comment]
What do you mean? run.sh cds to the directory. Have you pulled?

**Comment by karolherbst** [comment]
```
karol@karols-gentoo ~ $ pwd
/home/karol
karol@karols-gentoo ~ $ /usr/games/desurium/run.sh
```

le wild message box appears: "Desurium needs to be able to write to the root folder. Please fix the file permissions."

(using my "local" branch, wich is upstream + local changes)

**Comment by Jookia** [comment]
Yeah. I don't know why that is.

**Pull request merged**
