### PR TITLE
Bug577

### PR DESCRIPTION
**Pull request by makson96**
This pull request fix issue #577 for all supported languages. Note that I was mainly using Google Translator for languages other than Polish.

### CODE REVIEW

**Comment by karolherbst** [comment]
I don't think we should make translation with Google Translator. It would be better to let people do it, who are able to speak the languages.

**Comment by makson96** [comment]
Well, I know Russian good enough to see it is correct. For Finish and Esperanto those are only minor changes which seems ok to me (the singular form looks very similar to plural, which was previously present). But if you want me to revert Finish and Esperanto anyway, let me know.

**Comment by karolherbst** [comment]
I don't have a strong mind about Esperanto anyway. I will leave some notes in the commit

**Comment by karolherbst** [comment]
no, it seems okay

**Pull request merged**
