### PR TITLE
update dependency to 4.6 wrt Range-based for | N2930 | GCC 4.6

### PR DESCRIPTION
**Pull request by TheSiege**
There was a lot of trouble when people tried building desurium with gcc-4.5 on gentoo; I think we narrowed that done to 'Range-based for | N2930 | GCC 4.6'

### CODE REVIEW

**Comment by karolherbst** [comment]
Wie should drop  this dependency and do a check against active GCC version seen here: https://github.com/shiznix/unity-gentoo/blob/master/unity-base/unity/unity-5.18.0.ebuild#L62

**Comment by TheSiege** [comment]
not in the ebuild; all needed dependencies have to be listed; as gcc is slotted there is no problem
https://github.com/shiznix/unity-gentoo/blob/master/unity-base/unity/unity-5.18.0.ebuild#L47
but checking also against the active gcc is a good idea

**Comment by karolherbst** [comment]
And you should tag the commit with "ebuild:"

**Comment by karolherbst** [comment]
But here is more work to do, also in portage. What if you want to build desurium with another compiler...

**Comment by TheSiege** [comment]
seperate compilers would be controlledd over a useflag ( see clang useflag in eix); but I think we should aim to have one working ebuild in the gentoo tree before we experiment with making the ebuild good for different compilers

**Comment by karolherbst** [comment]
it is working for now, that's why I am worried about a pkg_pretend check.

I would like to have something like this:

if gcc && gcc version >= 4.6
|| if clang && clang version >= 3.0
|| if icc && icc version >= ??

**Comment by hasufell** [comment]
https://gist.github.com/d81b1f108601880a5a56

**Comment by karolherbst** [comment]
but how does "gcc-*-version" interact with other compilers? But I like the idea more than having an explicit dependency on gcc-4.6.

Or should we backport to gcc-4.5 instead? I don't know how common 4.6 is today. We should create an official dependency list we want to stick with.

**Comment by karolherbst** [comment]
I will open an issue for that

**Comment by hasufell** [comment]
https://gist.github.com/d81b1f108601880a5a56/2d3d3060d7c33dcf54855bb5e10e447fcc313512

**Comment by karolherbst** [comment]
this looks good. So we could also do some fancy stuff like: "if [[ $(tc-getCC) =~ clang ]]; then" and other version checks?

It would be awesome having multiple compiler support directly in portage, but I think that we should have something like that until 2014

**Comment by karolherbst** [comment]
Would be nice if you would fix #388 with this pull request. I would replace all the usage with the result.

**Pull request merged**
