### PR TITLE
Window fixes + gtest

### PR DESCRIPTION
**Pull request by lodle**
Clean up windows build to almost work.
Added gtest in, atm its just in the third_party folder due to it having its own cmake file. A smarter man might want to fix that.

### CODE REVIEW

**Comment by Jookia** [comment]
I'm a little concerned that the Travis CI build fails, that we're adding gtest to the repository instead of downloading it separately, and hardcoding 'bin' to be in the path for libcef_desura.dll. Also the instructions seem like something that may need to be updated later, but forgotten about.

Those are just my concerns. What do you think @karolherbst?

**Comment by karolherbst** [comment]
I will go throght the changes and will leave a comment later

**Comment by lodle** [comment]
visual 2013 is good for debugging (can step into lambdas) i wasnt meant to commit my boost build hack. 
Windows should stay the same as the official window build with a bin folder for dll's.
If you want/can you can add gtest to download, was 5 second change to get it to build this way
Gmock/gtest hasnt been sorted for linux yet
Not sure why there are missing files ill check tomorrow
Slashes need to be escaped in source code. i dont like this but ill talk to you more about it
chrono is needed as it didnt compile with out it

**Comment by lodle** [comment]
i want to talk to you about how best to make different changes as well. Hope to see you on irc tomorrow

**Comment by karolherbst** [comment]
yeah, I will have free the whole day tomorrow. Will be in IRC all the time after GMT9+2, maybe I will be there today, but distracted

**Comment by Jookia** [comment]
Could you rebase this on HEAD, and remove some stuff that's unrelated that'll be merged elsewhere? (ARMA, copypright, other stuff that's been merged?)

**Comment by Jookia** [comment]
Don't we already have Boost tests?

**Comment by lodle** [comment]
dont like boost tests, want them to run at start up as well.

**Comment by karolherbst** [comment]
I will close this request, because it will be updated by every lodle/master push. I have a local branch, where I clean up this stuff a bit. I've create already a pull request which is realted ot the first commits of this series

**Pull request closed without merging**
