### PR TITLE
Dependencies installation for Fedora

### PR DESCRIPTION
**Pull request by yurikoles**
Install-deps.sh now determines running distribution and runs corresponding installation command. For now support is limited to Debian-based and Fedora.

### CODE REVIEW

**Comment by yurikoles** [comment]
To test build we have to resolve problem with wxwidgets checkouting.

svn: warning: Error handling externals definition for 'wxWidgets/build/tools':
svn: warning: URL 'http://svn.wxwidgets.org/svn/wx/wxWidgets/tools/build' at revision 70437 doesn't exist

**Comment by lopho** [comment]
but its still a first point of orientation, better than knowing nothing about dependencies at all.

**Comment by Jookia** [comment]
While this is a good idea, I have a tingling feeling that Bash scripts aren't the way to do this, as it already looks like a horrid mess. Could this be rewritten in Python? Could you use a hash map for each package and it's distro's package? Could we allow gcc 4.6 and bigger?

**Comment by Jookia** [comment]
Alas, we have install-deps.sh already so I may as well merge this.

**Comment by Jookia** [comment]
But please reconsider using Bash for this.

**Comment by yurikoles** [comment]
Python is also dependency :)

**Comment by Jookia** [comment]
Python and Bash are both dependencies.

**Comment by yurikoles** [comment]
Bash is not required, the script is not bash-specific. 
Show me supported distribution without shell.

**Comment by Jookia** [comment]
I'm saying that that's a shell script, we already need Python, so it's not another dependency being pulled in.

**Comment by yurikoles** [comment]
Ok. What if user has no python installed? This script will install python as scons' dependency. When manipulations with system the shell is a must . We can also integrate support for other Unices.

Or we can install python with shell, then use python to install another dependencies. But “Beings
are not to be multiplied beyond necessity.”

**Comment by Jookia** [comment]
If the user has no python installed, they can't build Desura, as requires gyp, which requires Python.

This script will turn in to a mess if it's in a shell script.

**Comment by yurikoles** [comment]
> This script will install python as scons' dependency

**Comment by Jookia** [comment]
Yes, but this script is going to end up being a very long and complex file, and I think rewriting it in Python could stop that, or other measures. On IRC, Lodle suggested having a script for each distro.

**Pull request merged**
