### PR TITLE
cURL 7.21.5 & c-ares 1.7.5

### PR DESCRIPTION
**Pull request by boskee**
Updated cURL to version 7.21.5 and c-ares to 1.7.5. Fixes Issue #44: cURL needs to be updated to at least 7.21.5 as 7.21.4 won't compile on Debian/Ubuntu because of no SSLv2 support

### CODE REVIEW

**Comment by Jookia** [comment]
Does this include the patches?

**Comment by Jookia** [comment]
Ah, it seems Lodle didn't separate the patches. This is a bit of an issue. Could you do a diff of the original third_party curl and c-are source code with the official versions they're derived from, to find the files Lodle edited of the old version?

**Comment by boskee** [comment]
I did a diff on the original cURL 7.21.4 and original cURL 7.21.5 and patched third_party cURL with those changes. There was no rejects. Also, c-ares is pulled from its repo with third_party/SVNCheckout.sh script so there's nothing to patch.

**Comment by Jookia** [comment]
So the updated curl has the same changes as ye olde curl?
Also, could you get a diff of the changes purely for curisoity's sake?

**Comment by boskee** [comment]
Looks like my recent commit was included in this pull request. How can I exclude iand send it separately?

As for the diff - which one are you interested in? third_parthy/curl <> official 7.21.4 or official 7.21.4 <> official 7.21.5?

**Comment by Jookia** [comment]
You'd have to branch it. I don't know.

I want third_party/curl_7.21.4 -> official 7.21.4

**Comment by boskee** [comment]
Here you go http://pastebin.com/kfCsDURw

**Comment by Jookia** [comment]
Sorry, but I'm going to have to close this on account of it being a better idea to just checkout curl from SVN and patching it. Importing the entire source tree isn't a good idea for every update.

**Comment by boskee** [comment]
I agree, but right now curl is not in SVNCheckout scripts and there are no patches included. It's quite important to address, as right now Desurium fails to compile on Debian/Ubuntu because of that.

**Comment by Jookia** [comment]
If you'd like to make that happen it'd be great. It's just build scripts being fixed.

**Pull request closed without merging**
