### PR TITLE
Added virtual solution folders for visual studio

### PR DESCRIPTION
**Pull request by lodle**

### CODE REVIEW

**Comment by Jookia** [comment]
Looks good to me. What about your @karolherbst ?

**Comment by karolherbst** [comment]
Nothing of this should effect a non MSVC build at all, so I am fine with this.

The v8 stuff is just fixing a little compile error, when you have parallel builds (with jom instead of nmake for example)

**Comment by Jookia** [comment]
Merging then.

**Comment by Jookia** [comment]
If I can click merge properly, that is. :P

**Pull request merged**
